color: null
fieldLayouts:
  6ea642f5-1bb5-4c7d-95f7-0b656c7d09a6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-10T10:10:19+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 053bef32-05f7-40b9-9ed1-53a1e1c51381
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-10T10:11:27+00:00'
            elementCondition: null
            fieldUid: 162a3b3a-57cb-4b08-8ed7-ac54edd00b46 # Form
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ad4cdeda-7ede-4f48-abd4-6954d1dbea0f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0d2665ee-7aee-4cef-bf93-e97eb5b9b073
        userCondition: null
handle: contact
hasTitleField: true
icon: null
name: Contact
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
