defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 7be4b51f-c76c-48f0-9286-9d7382d6c18e # Home
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  dbc40939-7604-459d-8387-00103bbf7a2d: # Website
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: __home__
type: single
