isPublic: false
name: Website
scope:
  - 'sites.dbc40939-7604-459d-8387-00103bbf7a2d:read' # Website
  - 'elements.drafts:read'
  - 'elements.revisions:read'
  - 'elements.inactive:read'
  - 'sections.1cb4e6df-e2fc-47f3-b0f4-1a3cd7d30dd6:read' # Contact
  - 'sections.4a8904c4-a415-4548-9174-a7e834d34b66:read' # Home
  - 'volumes.0dc819e2-0bd9-4307-888c-3ca41203ec2d:read' # Uploads
  - 'formieForms.all:read'
  - 'formieForms.801cef1c-7439-4f7c-a5d8-f9532f01a48e:read'
  - 'formieForms.d9466e5a-c611-40cb-a802-ef6e2eb79999:read'
  - 'formieSubmissions.all:read'
  - 'formieSubmissions.801cef1c-7439-4f7c-a5d8-f9532f01a48e:read'
  - 'formieSubmissions.d9466e5a-c611-40cb-a802-ef6e2eb79999:read'
